### PR TITLE
Implements colorsys from the standard library to add HLS and HSV to RGB support

### PR DESCRIPTION
**Pull request by JovialJuggernaut**
Will return tuple of RGB[0-255] values.

### CODE REVIEW

**Comment by tannewt** [comment]
Is this code from somewhere else or did you write it? We should make sure and keep the license info on it.

**Comment by JovialJuggernaut** [comment]
It's a couple functions ripped out of colorsys.py in the anaconda3/lib folder.  It didn't have the license info in the script itself.

**Comment by tannewt** [comment]
Looks like its from CPython: https://github.com/python/cpython/blob/3.4/Lib/colorsys.py

Please add a comment saying so and refer to the license here: https://github.com/python/cpython/blob/3.4/LICENSE

Thank you!

**Comment by JovialJuggernaut** [comment]
Will that work?

Thanks!

**Comment by tannewt** [comment]
Yup! Looks great! Thanks!

**Pull request merged**
