### PR TITLE
Initial changes, including helper and styles file

### PR DESCRIPTION
**Pull request by jposada202020**
To include style helpers in the color helper library.  
For reference see https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/pull/143

### CODE REVIEW

**Comment by ladyada** [comment]
nice, wanna add some pylint-disable's in the file to resolve the CI complaints?

**Comment by jposada202020** [comment]
@ladyada plan is to convert this module in Adafruit_Colorsys (name TBC) module package. This will work for 
Include here:
* Styling colors and other for display widgets. This will allow have themes work the new and old widgets. as you can see in PR above and will allow us to generate colorset for all the widgets and displays that we support, so we can change themes.
* Color conversion utilities (from Colorsys, fancyled) if needed.

@FoamyGuy will convert this into a module, as you can see in issue #13 and we will work together in this.
and for sure :) I will make this pylint errors pass.

**Comment by FoamyGuy** [comment]
If I understood Scott and Kattni correctly I believe the plan is to convert this library to contain just the colorsys module.

Then we will create a new library like Adafruit_CircuitPython_Themes (or maybe Adafruit_CircuitPython_Styles) that will contain the theme definitions for importing. 

@jposada202020 have you ever used cookie cutter before? We'll need to run that to make a new project for that new Themes or Styles library.

**Comment by jposada202020** [comment]
@FoamyGuy 
Oh I see I misunderstood then. No problem.if that would be the case, there are some other color utilities in the PySimpleGui that we could add in this library.

I prefer also the name Adafruit_CircuitPython_Styles.
No, I am not familiar with cookie cutter, but I know there is a guide in the Adafruit Leaning System so I will explore it tonight

Thanks.

**Comment by jposada202020** [comment]
@FoamyGuy please take a look at the proposed new library. Still barebones, But I can, if this alpha could work I would go through all the display widgets to add the ability to use it. Thanks again for always helping me!!
https://github.com/jposada202020/Adafruit_CircuitPython_Styles

**Comment by kattni** [comment]
@FoamyGuy is correct.

@jposada202020 Are we good to close this PR then?

**Comment by jposada202020** [comment]
@kattni Yes. Thanks, Closing this now.

**Pull request closed without merging**
